fix: changes

diff --git a/.github/workflows/pullrequest.yml b/.github/workflows/pullrequest.yml
--- a/.github/workflows/pullrequest.yml
+++ b/.github/workflows/pullrequest.yml
@@ -1,4 +1,4 @@
-name: Pull Request CI
+name: pull-request-merge
 
 on:
   pull_request:
@@ -7,25 +7,8 @@ on:
       - synchronize
 
 jobs:
-  commit-lint:
-    runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: '18'
-      - name: Install dependencies
-        run: npm ci
-    
-      - name: Commitlint check
-        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
-
-  merge-blocking:
+  pull-request-merge:
     runs-on: ubuntu-latest
 
     steps:
@@ -45,28 +28,18 @@ jobs:
       - name: Eslint check
         run: npm run test
 
-      - name: Check CI status
-        id: check_status
+      - name: check
         uses: actions/github-script@v3
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
-            const { data: checks } = await github.checks.listForRef({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              ref: context.sha
-            });
-  
-            const failingChecks = checks.check_runs.filter((check) => check.conclusion === 'failure');
-  
-            if (failingChecks.length > 0) {
-              console.log('There are failing checks. Blocking merge.');
-  
-              core.setFailed('There are failing checks. Blocking merge.');
-            } else {
-              console.log('All checks passed. Allowing merge.');
-            }
-
-      - name: Set merge status
+             if ((await github.checks.listForRef({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                ref: context.sha
+              })).data.check_runs.some(check => check.conclusion === 'failure')) {
+                core.setFailed('There are failing checks. Blocking merge.');
+              }
+      - name: merge pull 
         if: ${{ failure() }}
-        run: echo "Merge blocked due to failing checks." && exit 1
+        run: echo "Failed Merge." && exit 1
